#!/bin/sh -ex
# $IMAGE_NAME var is injected into the build so the tag is correct.

exec docker build \
  --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M")" \
  --build-arg BUILD_VCS_REF="$(git rev-parse HEAD)" \
  --tag "${IMAGE_NAME}" .
